Add debug logs

diff --git a/.github/actions/check-merge-queue-changelogs/action.yml b/.github/actions/check-merge-queue-changelogs/action.yml
--- a/.github/actions/check-merge-queue-changelogs/action.yml
+++ b/.github/actions/check-merge-queue-changelogs/action.yml
@@ -55,11 +55,26 @@ runs:
         BRANCH=$(gh api "/repos/${REPOSITORY}/pulls/${PR_NUMBER} --jq=.head.ref")
         echo "pr-branch=$BRANCH" >> "$GITHUB_OUTPUT"
 
+    - name: Get target reference
+      id: get-target
+      shell: bash
+      env:
+        EVENT_NAME: ${{ github.event_name }}
+      run: |
+        if [ "$EVENT_NAME" = "pull_request" ]; then
+          echo "target=$GITHUB_HEAD_REF" >> "$GITHUB_OUTPUT"
+        elif [ "$EVENT_NAME" = "merge_group" ]; then
+          echo "target=$(git rev-parse HEAD^)" >> "$GITHUB_OUTPUT"
+        else
+          echo "::error::This action only supports \`pull_request\` and \`merge_group\` events."
+          exit 1
+        fi
+
     - name: Check changelog changes
       id: changelog-check
       shell: bash
       env:
-        REF: ${{ inputs.ref }}
+        TARGET_REF: ${{ steps.get-target.outputs.target }}
         BASE_REF: ${{ inputs.base-ref }}
         PR_BRANCH: ${{ steps.pr-branch.outputs.pr-branch }}
         REPOSITORY: ${{ github.repository }}
@@ -67,7 +82,12 @@ runs:
       run: |
         set -euo pipefail
 
-        UPDATED_CHANGELOGS=$(git diff --name-only origin/"$BASE_REF"...origin/"$PR_BRANCH" | grep -E 'CHANGELOG\.md$' || true)
+        echo "Comparing changes between origin/$TARGET_REF and origin/$PR_BRANCH"
+
+        UPDATED_CHANGELOGS=$(git diff --name-only "origin/$TARGET_REF..origin/$PR_BRANCH" | grep -E 'CHANGELOG\.md$' || true)
+
+        echo "Updated changelogs: $UPDATED_CHANGELOGS"
+
         if [ -n "$UPDATED_CHANGELOGS" ]; then
           for FILE in $UPDATED_CHANGELOGS; do
             git show origin/"$BASE_REF":"$FILE" > /tmp/base-changelog.md
